### PR TITLE
Added docs for plugin setup

### PR DESCRIPTION
**Pull request by benredmond**

### CODE REVIEW

**Review by BaibhaVatsa — COMMENTED** [review]
Looks good to me

Can you just add the following with their respective values so that it can reflect the values correctly in the docusaurus webpage?
```
---
id: 
title: 
sidebar_label: 
---
```

**Comment by benredmond** [comment]
@BaibhaVatsa not entirely sure where you wanted me to add the above values, but I did add a section in the sidebar.js file for the new docs

**Comment by BaibhaVatsa** [comment]
Sorry for the confusion. I meant at the start of the `setup.md` file.

**Review by BaibhaVatsa — APPROVED** [review]

**Comment by gfting** [comment]
Nice–looks good. Thank you for adding this!

**Pull request merged**
